#!/bin/sh
# Generate build metadata for runtime version display.
# Called during build: npm run build

GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH=$(git branch --show-current 2>/dev/null || echo "")
if [ -z "$GIT_BRANCH" ]; then
  GIT_BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME:-unknown}}"
fi
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
VERSION=$(node -p "require('./package.json').version" 2>/dev/null || echo "0.0.0")
PLATFORM=$(uname -s 2>/dev/null || echo "unknown")
ARCH=$(uname -m 2>/dev/null || echo "unknown")

cat > src/build-info.ts << EOF
// Auto-generated by scripts/generate-build-info.sh — do not edit manually.
export const BUILD_INFO = {
  version: '${VERSION}',
  gitHash: '${GIT_HASH}',
  branch: '${GIT_BRANCH}',
  buildDate: '${BUILD_DATE}',
  platform: '${PLATFORM}',
  arch: '${ARCH}',
};
EOF
